---
- hosts: all

  vars:
    myhostname: "{{ ansible_fqdn }}"
    myorigin: \\$mydomain
    relayhost: ""
    inet_interfaces: loopback-only
    aliases: []
    smtp_bind_address: ""

  tasks:
    - name: postfix | install
      apt: pkg=postfix state=latest update_cache=yes
      tags: postfix

    - name: postfix | configure
      lineinfile: dest=/etc/postfix/main.cf regexp="{{ item.regexp }}" line="{{ item.line }}" backup=yes
      with_items:
          - { regexp: "^myhostname", line: "myhostname = {{ myhostname }}" }
          - { regexp: "^myorigin", line: "myorigin = {{ myorigin }}" }
          - { regexp: "^mydestination", line: "mydestination = " }
          - { regexp: "^relayhost", line: "relayhost = {{ relayhost }}" }
          - { regexp: "^inet_interfaces", line: "inet_interfaces = {{ inet_interfaces }}" }
          - { regexp: "^virtual_maps =", line: "virtual_maps = hash:/etc/aliases" }
      notify: reload postfix
      tags: postfix

    - name: postfix | setup aliases
      lineinfile: "dest=/etc/aliases regexp='^{{ item.user }}:' line='{{ item.user }}: {{ item.alias }}' backup=yes"
      with_items: aliases
      when: aliases > 0
      notify: newaliases
      tags: postfix

    - name: postfix | setup smtp bind address
      lineinfile: dest=/etc/postfix/master.cf regexp="^{{ item }}\s+unix" insertafter="^{{ item }}\s+unix" line="{{ item }}      unix  -       -       -       -       -       smtp -o smtp_bind_address={{ smtp_bind_address }}" backup=yes
      with_items:
          - smtp
          - relay
      when: smtp_bind_address != ""
      notify: reload postfix
      tags: postfix

    - name: postfix | ensure service is running
      service: name=postfix state=started
      tags: postfix

  handlers:
    - name: newaliases
      command: newaliases

    - name: reload postfix
      service: name=postfix state=reloaded
