---
- hosts: all

  tasks:
    - name: postfix | install
      apt: pkg=postfix state=latest update_cache=yes
      tags: postfix

    - name: postfix | ensure service is running
      service: name=postfix state=started
      tags: postfix
