---
- hosts: web

  vars:
    extensions: []

  tasks:
    - name: php5 | install
      apt: pkg={{ item }} state=latest update_cache=yes
      with_items:
        - php5-common
        - php5-cgi
        - php5
      tags: php5

    - name: php5 | install extensions
      apt: pkg={{ item }} state=latest update_cache=yes
      with_items: extensions
      tags: php5

    - name: php5 | configure opcache
      template: src=templates/opcache.ini.j2 dest=/etc/php5/mods-available/opcache.ini backup=yes
      tags: php5
