---
- hosts: all

  vars:
    directories: []
    mysql: false
    mongodb: false
    jackrabbit: false
    targets: []
    tmp_dir: /var/backups
    executable: /usr/bin/backup
    full_time: 1W
    remove_time: 1M

  tasks:
    - name: duplicity | install
      apt: pkg={{ item }} state=latest update_cache=yes
      with_items:
        - duplicity
        - python-gobject-2
      tags: duplicity

    - name: duplicity | copy backup script
      template: src=templates/backup.sh.j2 dest={{ executable }} owner=root group=root mode=700
      tags: duplicity

    - name: duplicity | install cron
      cron: name="duplicity" user="root" minute="0" hour="6" job="nice -n 20 ionice -c3 {{ executable }} >> /var/log/duplicity.log"
      tags: duplicity
