---
- hosts: db

  vars:
    version: 1.3

  tasks:
    - name: elasticsearch | add repository key
      apt_key: url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch
      tags: elasticsearch

    - name: elasticsearch | add repository
      apt_repository: repo='deb http://packages.elasticsearch.org/elasticsearch/{{ version }}/debian stable main' update_cache=yes
      tags: elasticsearch

    - name: elasticsearch | install
      apt: pkg=elasticsearch state=latest update_cache=yes
      tags: elasticsearch

    - name: elasticsearch | ensure service is running
      service: name=elasticsearch state=started
      tags: elasticsearch
