---
- hosts: web

  vars:
      appname: "{{ ansible_fqdn }}"

  pre_tasks:
    - name: newrelic | install requirements
      apt: pkg=python-pycurl state=latest update_cache=yes
      tags: newrelic

  tasks:
    - name: newrelic | add repository key
      apt_key: url=https://download.newrelic.com/548C16BF.gpg
      tags: newrelic

    - name: newrelic | add repository
      apt_repository: repo='deb http://apt.newrelic.com/debian/ newrelic non-free' update_cache=yes
      tags: newrelic

    - name: newrelic | configure appname
      lineinfile: dest=/etc/php/7.0/mods-available/newrelic.ini regexp="newrelic.appname = " line='newrelic.appname = "{{ appname }}"' backup=yes
      tags: newrelic

    - name: newrelic | configure license
      lineinfile: dest=/etc/php/7.0/mods-available/newrelic.ini regexp="newrelic.license = " line='newrelic.license = "{{ newrelic_license }}"' backup=yes
      when: newrelic_license is defined
      tags: newrelic

    - name: newrelic | install server monitor
      apt: pkg=newrelic-sysmond state=latest update_cache=yes
      tags:
        - newrelic
        - php5

    - name: newrelic | configure server monitor license
      lineinfile: dest=/etc/newrelic/nrsysmond.cfg regexp="^license_key=" line="license_key={{ newrelic_license }}" backup=yes
      when: newrelic_license is defined
      tags: newrelic

    - name: newrelic | ensure server monitor is running
      service: name=newrelic-sysmond state=started
      tags: newrelic
