---
- hosts: web
  vars:
    ssl: false
    ssl_forward_secrecy_key_path: /etc/nginx/conf/dhparam.pem
    ssl_forward_secrecy_key_length: 2048
    upload_max_file_size: 2M
    large_client_header_buffers: 4 8k
    user: www-data
    vhosts: []
    limit_per_ip: 5

  tasks:
    - name: nginx | install
      apt: pkg=nginx state=latest update_cache=yes
      tags: nginx

    - name: nginx | copy config file
      template: src=templates/nginx.conf.j2 dest=/etc/nginx/nginx.conf owner=root group=root mode=0644
      notify: reload nginx
      tags: nginx

    - name: nginx | install openssl
      apt: pkg=openssl state=latest update_cache=yes
      when: ssl
      tags: nginx

    - name: nginx | generate ssl forward secrecy key
      command: openssl dhparam -out {{ ssl_forward_secrecy_key_path }} {{ ssl_forward_secrecy_key_length }} creates={{ ssl_forward_secrecy_key_path }}
      when: ssl
      tags: nginx

    - name: nginx | check ssl forward secrecy key
      file: path={{ ssl_forward_secrecy_key_path }} owner=root group=root mode=0600
      when: ssl
      tags: nginx

    - name: nginx | copy ssl config file
      template: src=files/conf.d/ssl.conf.j2 dest=/etc/nginx/conf.d/ssl.conf owner=root group=root mode=0644
      when: ssl
      notify: reload nginx
      tags: nginx

    - name: nginx | copy config files
      template: src={{ item }} dest=/etc/nginx/conf.d/ owner=root group=root mode=0644
      with_fileglob:
        - "{{ config_dir }}/*"
      notify: reload nginx
      tags: nginx

    - name: nginx | create scripts directory
      file: dest=/etc/nginx/scripts owner=www-data group=www-data state=directory
      tags: nginx

    - name: nginx | copy scripts files
      template: src={{ item }} dest=/etc/nginx/scripts/ owner=root group=root mode=0755
      with_fileglob:
        - "files/scripts/*"
      tags: nginx

    - cron: name="refresh stopspamforum" user="root" hour="0,8,16" minute="0" job="/etc/nginx/scripts/stopforumspam > /dev/null"
      tags:
        - nginx
        - crontab

    - name: nginx | disable default virtual host
      file: dest=/etc/nginx/sites-enabled/default state=absent
      notify: reload nginx
      tags:
        - nginx
        - vhost

    - name: nginx | copy virtual host
      template: src={{ vhosts_dir }}/{{ item.src }} dest=/etc/nginx/sites-available/{{ item.dest }} owner=root group=root mode=0644
      with_items: vhosts
      notify: reload nginx
      tags:
        - nginx
        - vhost

    - name: nginx | enable virtual host
      file: src=../sites-available/{{ item.dest }} dest=/etc/nginx/sites-enabled/{{ item.dest }} owner=root group=root state=link force=yes
      with_items: vhosts
      notify: reload nginx
      tags:
        - nginx
        - vhost

    - name: nginx | copy symfony2 config file
      copy: src=files/symfony2-php7.0 dest=/etc/nginx/symfony2 owner=root group=root mode=0644
      notify: reload nginx
      tags: nginx

    - name: nginx | create /var/www directory
      file: dest=/var/www owner=www-data group=www-data state=directory
      tags: nginx

    - name: nginx | use bash for www-data
      command: chsh -s /bin/bash www-data
      tags: nginx

    - name: nginx | allow www-data to clear opcode
      lineinfile: "dest=/etc/sudoers state=present regexp='^www-data ALL=' line='www-data ALL= NOPASSWD: /etc/init.d/clear-opcode' validate='visudo -cf %s'"
      tags: nginx

    - name: nginx | ensure service is running
      service: name=nginx state=started
      tags: nginx

  handlers:
    - name: reload nginx
      service: name=nginx state=reloaded
