---
- hosts: web
  vars:
    ssl: false
    upload_max_file_size: 2M
    large_client_header_buffers: 4 8k
    user: www-data
    vhosts: []

  tasks:
    - name: nginx | install
      apt: pkg=nginx state=latest update_cache=yes
      tags: nginx

    - name: nginx | copy config file
      template: src=templates/nginx.conf.j2 dest=/etc/nginx/nginx.conf owner=root group=root mode=0644
      notify: reload nginx
      tags: nginx

    - name: nginx | copy ssl config file
      template: src=files/conf.d/ssl.conf.j2 dest=/etc/nginx/conf.d/ssl.conf owner=root group=root mode=0644
      when: ssl
      notify: reload nginx
      tags: nginx

    - name: nginx | copy config files
      template: src={{ item }} dest=/etc/nginx/conf.d/ owner=root group=root mode=0644
      with_fileglob:
        - "{{ config_dir }}/*"
      notify: reload nginx
      tags: nginx

    - name: nginx | disable default virtual host
      file: dest=/etc/nginx/sites-enabled/default state=absent
      notify: reload nginx
      tags:
        - nginx
        - vhost

    - name: nginx | copy virtual host
      template: src={{ vhosts_dir }}/{{ item.src }} dest=/etc/nginx/sites-available/{{ item.dest }} owner=root group=root mode=0644
      with_items: vhosts
      notify: reload nginx
      tags:
        - nginx
        - vhost

    - name: nginx | enable virtual host
      file: src=../sites-available/{{ item.dest }} dest=/etc/nginx/sites-enabled/{{ item.dest }} owner=root group=root state=link force=yes
      with_items: vhosts
      notify: reload nginx
      tags:
        - nginx
        - vhost

    - name: nginx | copy symfony2 config file
      copy: src=files/symfony2 dest=/etc/nginx/symfony2 owner=root group=root mode=0644
      notify: reload nginx
      tags: nginx

    - name: nginx | create /var/www directory
      file: dest=/var/www owner=www-data group=www-data state=directory
      tags: nginx

    - name: nginx | use bash for www-data
      command: chsh -s /bin/bash www-data
      tags: nginx

    - name: nginx | allow www-data to clear opcode
      lineinfile: "dest=/etc/sudoers state=present regexp='^www-data ALL=' line='www-data ALL= NOPASSWD: /etc/init.d/clear-opcode' validate='visudo -cf %s'"
      tags: nginx

    - name: nginx | ensure service is running
      service: name=nginx state=started
      tags: nginx

  handlers:
    - name: reload nginx
      service: name=nginx state=reloaded
