---
- hosts: all

  vars:
      allow_ssh_root_user: without-password

  tasks:
    - name: rkhunter | install
      apt: pkg=rkhunter state=latest update_cache=yes
      tags: rkhunter

    - name: rkhunter | update
      command: rkhunter --propupd
      tags: rkhunter

    - name: rkhunter | configure
      lineinfile: dest=/etc/rkhunter.conf regexp="{{ item }}" line="{{ item }}" backup=yes
      with_items:
        - ^ALLOW_SSH_ROOT_USER={{ allow_ssh_root_user }}
        - ^ALLOWHIDDENDIR=\"/etc/.java\"
        - ^SCRIPTWHITELIST=\"/usr/bin/unhide.rb\"
      tags: rkhunter

    - name: rkhunter | configure cron
      lineinfile: dest=/etc/default/rkhunter regexp="^CRON_DAILY_RUN" line='CRON_DAILY_RUN="yes"' backup=yes
      tags: rkhunter
