---
- hosts: all

  tasks:
    - name: common | install packages
      apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
      with_items:
         - git
         - htop
         - vim
         - locales-all
         - python-pycurl
         - bash-completion
         - sudo
      tags: common

    - name: common | configure prompt
      lineinfile: dest=/etc/bash.bashrc regexp="^PS1=" line="PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '" backup=yes
      tags: common

    - name: common | copy bash config files
      copy: src=files/aliases.sh dest=/etc/profile.d/aliases.sh
      tags: common
