---
- hosts: all

  vars:
    timezone: UTC

  tasks:
    - name: common | install packages
      apt: pkg={{ item }} state=latest update_cache=yes
      with_items:
         - git
         - htop
         - vim
         - locales-all
         - python-pycurl
         - bash-completion
         - sudo
         - ntp
      tags: common

    - name: common | set hostname
      hostname: name={{ hostname }}
      when: hostname is defined
      tags: common

    - name: common | configure prompt
      lineinfile: dest=/etc/bash.bashrc regexp="^PS1=" line="PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '" backup=yes
      tags: common

    - name: common | copy bash config files
      copy: src=files/aliases.sh dest=/etc/profile.d/aliases.sh
      tags: common

    - name: common | set vim as default editor
      command: update-alternatives --set editor /usr/bin/vim.basic
      tags: common

    - name: common | configure vim
      copy: src=files/vimrc dest=/etc/vim/vimrc.local
      tags: common

    - name: common | configure git
      copy: src=files/gitconfig dest=/etc/gitconfig
      tags: common

    - name: common | configure timezone
      copy: content={{ timezone }} dest=/etc/timezone owner=root group=root mode=644 backup=yes
      notify: update timezone
      tags: common

    - name: common | configure localtime
      file: src=/usr/share/zoneinfo/{{ timezone }} dest=/etc/localtime owner=root group=root mode=644 state=link force=yes backup=yes
      tags: common

  handlers:
    - name: update timezone
      command: dpkg-reconfigure --frontend noninteractive tzdata
