---
- hosts: web

  tasks:
    - name: Test | NPM is installed
      shell: npm -v
      register: npm_installed
      ignore_errors: true
      tags: nodejs

    - name: NodeJS | Install curl
      apt: name=curl state=present

    - name: NodeJS | Prepare for installation
      raw: "curl -sL https://deb.nodesource.com/setup_6.x | sudo bash -"
      sudo: true
      when: npm_installed|failed

    - name: NodeJS | Install NodeJS
      apt: name=nodejs state=present

    - name: NodeJS | Install build-essentials package
      apt: name=build-essential state=present

    - name: nodejs | install packages
      npm: name={{ item }} global=yes
      with_items: packages
      tags: nodejs
