---
- hosts: web

  vars:
    node_version: "6.9.5"
    node_prefix: "node-v{{ node_version }}"
    node_tarball: "{{ node_prefix }}.tar.gz"
    node_path: "/usr/local"
    packages: []

  tasks:
    - name: nodejs | check installation
      shell: /usr/bin/test "$(node -v 2> /dev/null)" = v{{ node_version }}
      register: wanted_version_installed
      ignore_errors: true
      tags: nodejs

    - name: nodejs | install prerequisite
      apt: pkg={{ item }} update_cache=yes
      with_items:
        - make
        - gcc
        - g++
      when: wanted_version_installed.rc == 1
      tags: nodejs

    - name: nodejs | download
      get_url: url=http://nodejs.org/dist/v{{ node_version }}/{{ node_tarball }} dest=/tmp/
      when: wanted_version_installed.rc == 1
      tags: nodejs

    - name: nodejs | extract
      command: tar zxf {{ node_tarball }} chdir=/tmp
      when: wanted_version_installed.rc == 1
      tags: nodejs

    - name: nodejs | configure
      shell: python ./configure --prefix={{ node_path }} chdir=/tmp/{{ node_prefix }}
      when: wanted_version_installed.rc == 1
      tags: nodejs

    - name: nodejs | compile
      shell: make chdir=/tmp/{{ node_prefix }}/
      when: wanted_version_installed.rc == 1
      tags: nodejs

    - name: nodejs | install
      shell: make install chdir=/tmp/{{ node_prefix }}/
      when: wanted_version_installed.rc == 1
      tags: nodejs

    - name: nodejs | add NODE_PATH environment variable
      lineinfile: dest=/etc/environment regexp='^export NODE_PATH=' line='export NODE_PATH=/usr/local/lib/node_modules'
      tags: nodejs

    - name: nodejs | install packages
      npm: name={{ item }} global=yes
      with_items: packages
      tags: nodejs
